[theme]
base = "light"
primaryColor = "#6C50F3"
backgroundColor = "#F4F5FF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#18105C"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
